### ISSUE TITLE
very cool

### ISSUE THREAD

**Issue by gedw99** [vilterp/treesql#3]
This is an awesome prototype. I think there is a huge need for something that brings so many things together like this does.

My first idea when playing around is that maybe you want to add live queries as long term subscriptions later. For example:
You register for changes on a table and turn off the wifi on the device.
You come back a day later and any changes to those things your subscribed for are sent to you.

This whole thing feeds into of course a discussion about Service workers and caches.

**Comment by vilterp** [comment]
Thanks @gedw99! The long-term subscriptions idea is interesting. Maybe this could be implemented as an intermediary on the server side which subscribes to a live query and pushes the result out to the client if it's connected, or to a persistent log if it isn't.

And yes, would love to have a nice library to interact with service workers and caches down the line.

**Comment by gedw99** [comment]
:)
